### ISSUE TITLE
1.20(.1) Support

### ISSUE THREAD

**Issue by bwilliance** [shateq/TNTTime#6]
1.20 came out, and 1.20.1 came out quickly after, which didn't effect most mods that were made for 1.20 anyways. This mod is for 1.19.3, but it crashes on the latest version of Minecraft.

**Comment by shateq** [comment]
Gonna get to it THIS SUNDAY
I respect that someone is using this

**Comment by skibidibada** [comment]
...so uhh... about that "this sunday"?

**Comment by shateq** [comment]
I didn't expect so much (not much but much for me) voice from its users, fantastic. I promise I won't let you down next time!
